spring:
  application:
    name: task-service
  datasource:
    url: jdbc:mysql://localhost:3306/task
    username: root
    password: password
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
