spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: password

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true

server:
  port: 8092

#task-service:
#  ribbon:
#    listOfServers: http://localhost:8083,http://localhost:8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
testing:
  property: testing1

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: 
          -"*"
